language: python
python:
  - "3.6.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
before-script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'home#5775';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres
script:
  - pytest --cov=app/
  - coveralls
after_success:
  - coveralls
