language: python
python:
  - "3.6.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
before-script:
  - psql -c "CREATE USER testuser WITH PASSWORD 'testpass';" -U postgres
  - psql -c "CREATE DATABASE testdb;" -U postgres
script:
  - pytest --cov=app/
  - coveralls
after_success:
  - coveralls
