language: python
python:
  - "3.6.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
before-script:
  - psql -c 'create database test_db;' -U postgres
script:
  - pytest --cov=app/
  - coveralls
after_success:
  - coveralls
