language: python
python:
  - "3.6.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
before-script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'test_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;" -U postgres
script:
  - pytest --cov=app/
  - coveralls
after_success:
  - coveralls
